branch-defaults:
  default:
    environment: flask-env
environment-defaults:
  flask-env:
    branch: null
    repository: null
global:
  application_name: minerva
  default_ec2_keyname: aws-eb
  default_platform: Python 3.7
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application

commands:
  install-sql-stuff:
    command: sudo yum install mysql-devel gcc gcc-devel python-devel -y
  other-sql-stuff:
    command: sudo easy_install mysql-python
